spring.application.name=crypto_payment_gateway
server.port=8888

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5555/cpg
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

# Flyway
spring.flyway.enabled=true

# JWT Configuration
jwt.secret=256-bits-long-for-hs256
jwt.expiration=86400000